name: l4d2server
services:
  l4d2-1:
    image: l4d2tes/l4d2:1.1
    network_mode: host
    restart: always
    container_name: l4d2vs-1
    environment:
      PORT: 27015
      DEFAULT_MAP: c2m1_highway
      TICKRATE: 100
    volumes:
      - /etc/localtime:/etc/localtime:ro
  l4d2-2:
    image: l4d2tes/l4d2:1.1
    network_mode: host
    restart: always
    container_name: l4d2vs-2
    environment:
      PORT: 27016
      DEFAULT_MAP: c2m1_highway
      TICKRATE: 100
    volumes:
      - /etc/localtime:/etc/localtime:ro